In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#read data set 

In [ ]:
features = pd.read_csv('/content/drive/MyDrive/Customer_ Churn_Prediction/EDA/features_data.csv')
labels = pd.read_csv('/content/drive/MyDrive/Customer_ Churn_Prediction/EDA/labels_data.csv')


In [ ]:
features.shape

(4250, 28)

In [ ]:
labels.shape

(4250, 1)

In [ ]:
features.head()

col_0  col_1  col_2  ...  area_code_408  area_code_415  area_code_510
0      0      0      0  ...            0.0            1.0            0.0
1      0      1      0  ...            0.0            1.0            0.0
2      0      0      0  ...            1.0            0.0            0.0
3      0      0      0  ...            0.0            1.0            0.0
4      0      0      0  ...            0.0            0.0            1.0

[5 rows x 28 columns]

In [ ]:
labels.head()

churn
0      0
1      0
2      0
3      0
4      0

In [ ]:
#split data into train,test 

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test , y_train, y_test = train_test_split(features, labels , test_size=0.3, random_state=1)

In [ ]:
x_train.head()

col_0  col_1  col_2  ...  area_code_408  area_code_415  area_code_510
4169      1      0      0  ...            0.0            0.0            1.0
151       1      0      0  ...            0.0            0.0            1.0
1032      0      1      0  ...            0.0            0.0            1.0
460       0      0      1  ...            1.0            0.0            0.0
2383      0      0      1  ...            0.0            1.0            0.0

[5 rows x 28 columns]

In [ ]:
x_train.dtypes

col_0                              int64
col_1                              int64
col_2                              int64
col_3                              int64
col_4                              int64
col_5                              int64
col_6                              int64
col_7                              int64
account_length                   float64
international_plan                 int64
voice_mail_plan                    int64
number_vmail_messages            float64
total_day_minutes                float64
total_day_calls                  float64
total_day_charge                 float64
total_eve_minutes                float64
total_eve_calls                  float64
total_eve_charge                 float64
total_night_minutes              float64
total_night_calls                float64
total_night_charge               float64
total_intl_minutes               float64
total_intl_calls                 float64
total_intl_charge                float64
number_customer_

In [ ]:
x_train.iloc[0]

col_0                            1.000000
col_1                            0.000000
col_2                            0.000000
col_3                            0.000000
col_4                            0.000000
col_5                            0.000000
col_6                            0.000000
col_7                            0.000000
account_length                   0.869565
international_plan               0.000000
voice_mail_plan                  1.000000
number_vmail_messages            0.400000
total_day_minutes                0.554983
total_day_calls                  0.355769
total_day_charge                 0.555106
total_eve_minutes                0.158109
total_eve_calls                  0.672897
total_eve_charge                 0.157757
total_night_minutes              0.519940
total_night_calls                0.598131
total_night_charge               0.520067
total_intl_minutes               0.460432
total_intl_calls                 0.100000
total_intl_charge                0

In [ ]:
y_train.head()

churn
4169      0
151       0
1032      0
460       1
2383      0

In [ ]:
#from EDA we find that the data is unbalanced so we will upsampling data 

In [ ]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(sampling_strategy = 1, random_state=1)   
x_train_s, y_train_s = sm.fit_resample(x_train, y_train.values.ravel())
                                         

/usr/local/lib/python3.7/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
print('After upsampling count of label 0 {}'.format(sum(y_train_s==0)))
print('After upsampling count of label 1 {}'.format(sum(y_train_s==1)))

After upsampling count of label 0 2557
After upsampling count of label 1 2557


In [ ]:
#compare between classifcation models to choose best one 
#1-random forest
#2-Support Vector classifier 
#3-Logistic Regression


In [ ]:
#we care the most for the false negative 
#we need to reduce the number of chrun clients that the model predict that the won't chrun 

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import cohen_kappa_score
from xgboost import XGBClassifier

In [ ]:
#1-Random forest 
rfc = RandomForestClassifier()
rfc.fit(x_train_s, y_train_s)
y_pred = rfc.predict(x_test)
print('Classification report: ')
print('{}'.format(classification_report(y_test, y_pred)))
print('Confusion Matrix')
print('{}'.format(confusion_matrix(y_test, y_pred)))


Classification report: 
              precision    recall  f1-score   support

           0       0.93      0.96      0.94      1095
           1       0.68      0.54      0.60       180

    accuracy                           0.90      1275
   macro avg       0.80      0.75      0.77      1275
weighted avg       0.89      0.90      0.89      1275

Confusion Matrix
[[1049   46]
 [  82   98]]


In [ ]:
#support vector classifier
svc = SVC(kernel='rbf', decision_function_shape='ovr')
svc.fit(x_train_s, y_train_s)
y_pred = svc.predict(x_test)
print('Classification report: ')
print('{}'.format(classification_report(y_test, y_pred)))
print('Confusion Matrix')
print('{}'.format(confusion_matrix(y_test, y_pred)))


Classification report: 
              precision    recall  f1-score   support

           0       0.91      0.83      0.87      1095
           1       0.34      0.52      0.41       180

    accuracy                           0.79      1275
   macro avg       0.63      0.68      0.64      1275
weighted avg       0.83      0.79      0.81      1275

Confusion Matrix
[[912 183]
 [ 86  94]]


In [ ]:
#LogisticRegression
from sklearn.linear_model import LogisticRegression
lrc = LogisticRegression()
lrc.fit(x_train_s, y_train_s)
y_pred = lrc.predict(x_test)
print('Classification report: ')
print('{}'.format(classification_report(y_test, y_pred)))
print('Confusion Matrix')
print('{}'.format(confusion_matrix(y_test, y_pred)))

Classification report: 
              precision    recall  f1-score   support

           0       0.93      0.71      0.80      1095
           1       0.27      0.66      0.38       180

    accuracy                           0.70      1275
   macro avg       0.60      0.68      0.59      1275
weighted avg       0.83      0.70      0.74      1275

Confusion Matrix
[[778 317]
 [ 62 118]]


In [ ]:
#we care about false negative and false positive 
#false negative means that the model predict that the client won't chrun but it chrun 
#so we care aboout recall 
#Here the highest value for recall find in logitistic model 

In [ ]:
#fine tuning the logistic regression parameters to get better model

In [ ]:
#Step 1 - Import the library - GridSearchCv
import numpy as np
from sklearn import linear_model, decomposition, datasets
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler

In [ ]:
logistic_Reg =LogisticRegression()

In [ ]:
 pipe = Pipeline(steps=[('logistic_Reg', logistic_Reg)])

In [ ]:
#Logistic Regression requires two parameters 'C' and 'penalty' to be optimised by GridSearchCV. So we have set these two parameters
# as a list of values form which GridSearchCV will select the best value of parameter.
C = np.logspace(-4, 4, 50)
penalty = ['l1', 'l2']

In [ ]:
#Now we are creating a dictionary to set all the parameters options for different modules
parameters = dict(logistic_Reg__C=C,logistic_Reg__penalty=penalty)

In [ ]:
#Using GridSearchCV and Printing Results

In [ ]:
clf_GS = GridSearchCV(pipe,parameters)
clf_GS.fit(x_train_s, y_train_s)

In [ ]:
print('Best Penalty:', clf_GS.best_estimator_.get_params()['logistic_Reg__penalty'])
print('Best C:', clf_GS.best_estimator_.get_params()['logistic_Reg__C'])
   

Best Penalty: l2
Best C: 0.009102981779915217


In [ ]:
from sklearn.linear_model import LogisticRegression
best_lrc=LogisticRegression(C=0.0009102981779915217,penalty='l2')
#LogisticRegression
#from sklearn.linear_model import LogisticRegression
best_lrc.fit(x_train_s, y_train_s)
y_pred = best_lrc.predict(x_test)
print('Classification report: ')
print('{}'.format(classification_report(y_test, y_pred)))
print('Confusion Matrix')
print('{}'.format(confusion_matrix(y_test, y_pred)))

Classification report: 
              precision    recall  f1-score   support

           0       0.92      0.63      0.75      1095
           1       0.23      0.67      0.34       180

    accuracy                           0.64      1275
   macro avg       0.58      0.65      0.55      1275
weighted avg       0.82      0.64      0.69      1275

Confusion Matrix
[[693 402]
 [ 59 121]]


In [ ]:
### Create a Pickle file using serialization 
import pickle


In [ ]:
pickle_out = open("logistic_Reg_classifier.pkl","wb")
pickle.dump(best_lrc, pickle_out)
pickle_out.close()

In [ ]:
#test model 
example= [[1.000000,0.000000, 0.000000,0.000000, 0.000000,0.000000,0.000000,0.000000, 
     0.869565,0.000000,1.000000, 0.400000,0.554983,0.355769,0.555106, 0.158109, 0.672897,0.157757,
     0.519940,0.598131, 0.520067,0.460432,0.100000, 0.461333,0.333333,  0.000000,0.000000, 1.000000]]

In [ ]:
pred=best_lrc.predict(example)[0]


In [ ]:
print(pred)

0


In [ ]:
if pred==0:
  print('Will stay')
else:
  print('will chrun')  

Will stay


## Conclusion
Here I will give data to different machine learning models and then decide which is better 

But before that, the data  need to be splited into train, test 

from EDA we find that the data is unbalanced so we will upsampling data 
 
**compare between classifcation models to choose the best one**

1-random forest

2-Support Vector classifier 

3-Logistic Regression
 
we care about false negative and false positive 

false negative means that the model predict that the client won't chrun but it chrun 

so we care aboout recall 

Here is the highest value for **recall** find in logitistic model 
fine tuning the logistic regression parameters by using gridsearch to get a better model
 
**Logistic Regression** requires two parameters 'C' and 'penalty' to be optimised by GridSearchCV. So we have set these two parameters
as a list of values form which GridSearchCV will select the best value of the parameter.

**the best parameters** 

1-Penalty: l2

2-C: 0.009102981779915217
 
**Last step**

Save the model parameter in a packle file to use the model in FastAPI
 
 
 
 
 
